---
title: "Badge Challenges"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: no
---

<style>
h1{font-weight: 400;}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=TRUE, 
  message=FALSE, 
  warning=FALSE, 
  eval=FALSE, 
  fig.width=16/2, 
  fig.height=9/2
)
library(tidyverse)
library(gapminder)
library(patchwork)
```

<!--
{target="_blank"}
-->

***



# Badge Challenge System

There will be four "badge challenges," three mid-semester and one during finals week, during which you can collect statistics "badges." There are a total 15 badges, each representing a core skill for the course. Note: The coloring of the badge challenges matches the coloring of the lecture schedule.

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQM-5FVt5BKJZsfElEV19NwD2MXGgSVUfGLB7dUoD0MbCU6Dkzqx66UMxbgqMaiS6H8CP8numV5Xaf-/pubhtml?gid=67598343&amp;single=true&amp;widget=true&amp;headers=false" width="100%" height="550"></iframe>

As you can see, the first badge challenge will have the first 5 badges available, the second will have the first 10, and the third and fourth badge challenge will have all 15 badges. During each badge challenge, you can attempt as many or as few of the available badges as you would like. **Your goal, by the end of the semester, is to collect all 15 badges.** 

There are four levels for each badge: *G* – Gold, *S* – Silver, *B* – Bronze, and *X* – cannot be assessed. The most recent level for each badge is the recorded level. This means that if you earn a gold level for badge 1 on the first challenge, then you never have to attempt this badge again. But, if you earn silver for badge 4 on the first challenge and then a bronze for badge 4 on the second challenge, your current level for badge 4 is bronze. **Thus, you do not need to (nor should you) attempt all badges on each challenge,** but you do need to collect all 15 badges by the end of the term.

At the end of the semester, your collected badges and badge levels will be converted into points for the 45% of your final grade assigned to badge challenges (see [syllabus](syllabus.html#evaluation)):


<!--
Generated with: https://www.tablesgenerator.com/markdown_tables
-->
| Points | G  | S | B | X |
|--------|----|---|---|---|
| 45 pts | 15 | 0 | 0 | 0 |
| 40 pts | 11 | 3 | 1 | 0 |
| 36 pts | 7  | 5 | 2 | 1 |
| 32 pts | 3  | 5 | 4 | 3 |
| 27 pts | 1  | 4 | 5 | 5 |


**Why are we doing this?**

1. To remove the pressure, stress, and performance anxiety associated with conventional exams. The "badge challenge" system *guarantees* more than one chance to **master** each badge.
1. The "badge challenge" system system allows for you to iteratively improve your statistical skills throughout the semester. Each badge challenge is an opportunity for you to practice the *only* the statistical skills that you are ready to demonstrate. For example, if you've already **mastered** a particular badge, you can focus your studying elsewhere in a targeted fashion.
1. Since you are given the opportunity to **master** all 15 badges after the first three badge challenges, the fourth badge challenge during exam week becomes merely an opportunity to revise and improve your grade.
1. The "badge challenge" system is aligned with the **mastery**-based learning pedagogical paradigm, which encourages a ["growth mindset"](https://hapara.com/blog/mastery-based-grading/){target="_blank"} as opposed to a minimum/fixed mindset. 

<!--
Sell it informally as:

* Chart your own journey
* Pokemon: gotta catch them all
-->


***


# Badge Challenge I {#challengeI}

## Administrative notes

* Time window: **Friday 2/28 5pm through Monday 3/2 11pm**. In order to ensure fairness, all instructors, lab instructors, and Spinelli tutors will not answer questions about the badge challenge during this time window.
* In preparation for badge challenge:
    + Look at the [cover page](static/BC1_cover_page.pdf){target="_blank"}
    + Especially if you have never taken a Seelye Self-scheduled exam before, read the [instructions](http://www.science.smith.edu/self-scheduled-exam-printing/){target="_blank"} beforehand
    + Bring colored pencils/pens
    + All Office of Disability Services forms must be submitted to instructor in print before the start of the time window
* Printing the badge challenge: From a macOS computer in Seelye basement during the time window
    + Access the link to print the badge challenge on Moodle
    + Print badge challenge **in color**
    + At some point you'll need to wait 5-10 seconds for a "paper is held in queue" pop-up box to appear before you can print
* During badge challenge:
    + Closed-book, no internet, and individually completed
    + Remember that you only have to do as many questions as you are ready for. If a question has multiple parts, you **must** attempt all parts to earn above *X* (cannot be assessed). 
    + You will be given 140 mins to complete it (including transit time to writing area). **Timestamps will be strictly enforced. Any badge challenges with pairs of timestamps indicating than more than 140 minutes or missing timestamps are subject to an honor board case.**
* After badge challenge:
    + You are prohibited by the Honor Code from discussing the badge challenge until the end of the time window.


## Badges 1-5

### Topics

Everything we have done so far in this class is mapped to Badges 1-5 in the above table of 15 badges. In other words, everything up to and including regression with a categorical explanatory variable. Just like with the Grammar of Graphics where you map variables to aesthetics attributes, map everything we've done in class so far to one of 5 badges. By "everything" we mean:

1. Lectures 1-12: Content on course webpage for each lecture along with in-class notes
1. All the ModernDive readings in the course schedule along with learning checks (solutions are in Appendix-D of ModernDive)
1. Labs 1-4 and corresponding PS01-PS04

### How to study and take badge challenge

After you've done this, create a priority of badges from most to least comfortable, and plan to do the questions in that order during the badge challenge. That way you can demonstrate your strongest statistical knowledge first, lock those badges in, then with time permitting move on to attempt badges relating to your areas for development. Our past experience has shown that those students who:

1. First attempted 4 out of 5 badges then
1. Went back and polished their answers then
1. Attempted the remaining fifth question

often tended to catch small mistakes and thus were better able to demonstrate demonstrate badge proficiency. The badge challenge is timed such that if you have prepared adequately, we expect the majority students should be able to finish and revise 4 out of 5 questions comfortably and have sufficient time to potentially complete the remaining 5th badge.

> Remember that you only have to do as many questions as you are ready for. If a question has multiple parts, you **must** attempt all parts to earn above *X* (cannot be assessed). 

### Badge 2: What is "pseudocode"?

Badge challenge 2 is "Write pseudocode for basic data wrangling & exploratory data analysis." What is pseudocode? Think of pseudocode as a recipe, a blue print, or an algorithm outline that balances:

1. Being specific enough that someone who reads it can walk through the steps unambiguously.
1. Not being perfectly written code that necessarily works.

Code without explanation provides a limited view into your understanding. Therefore it is important to demonstrate mastery of the "what" we are doing (the recipe, blue print, outline) versus the "how" we are going to do it (actual functioning code).

In-class example:



***



# Revised Format {#challenge-format}

<!--
https://docs.google.com/document/d/1tHFupDpC1ZeoTeJAOk4_D0uAatG9n19nmmUGkrH6y7w/edit
-->

In this new phase of the course, we are adjusting the badge challenges to follow a **self-graded** model. This model is used by certain members of Smith's Engineering Department and this semester is being expanded in some engineering classes to their exams. 

## Motivation

As stated on our COVID-19 Information document, our overarching theme for the rest of the semester is **Maximal Flexibility**. The world has changed, and your learning spaces and environments have changed drastically. We believe that employing a version of self-graded badge challenges provides  for 1) greater flexibility than trying to "proceed as normal" and 2) more equity across variations in living situations and learning environments. All this while still retaining the badge challenge system's core philosophy of "mastery-based learning."


## Logistics

First and foremost, yes, there are still badge challenges. But how they are deployed is now in a three stage process. Below lists how this will work: 

* There are still badge challenge "windows", but they are longer than the Seelye self-scheduled window we had for badge challenge 1. 
* The maximum number of badges that you can turn in at the end of the Phase 3 is 7. After describing the process, there is a FAQ section where we will justify the reasoning behind our decisions. 

Phase 1 - Initial solutions for badge challenge questions

* This phase resembles the "usual" model where you will have 3 hours from the time you download the badge challenge from Moodle and when you stop working. Note you have 3h instead of 2h20min.
* You are not required to print the badge challenge. Rather, you only need to download it onto a device to view it. 
* Just as with Badge Challenge 1, you are completing the badge challenge on paper without the aid of a computing device (except to view the badge challenge questions), your class notes, or the textbook. 
* In this phase, each question should be on its own page. In other words, do not try to squeeze two questions or parts of two questions onto the same physical page. 
* In this phase, only the questions that you attempt "move on" to Phase 2 . 

Phase 2 - Checking your Phase 1

* In this phase, you will upload your Phase 1 on Moodle and then automatically get access to the instructor-created solution guide. 
* To create a PDF of all of your answers to submit, we recommend using either:
    1. A scanner if you have access to one 
    1. The CamScanner on a smartphone
    1. Creating photos using your computer's camera and then converting these photos to PDF
* Note that the time to scan and upload your file is NOT part of your 3 hour window in Phase 1. 
* Once you have the solutions, you will correct your Phase 1 work in a different color ink.  Please choose colors that are radically different from each other so that we can easily distinguish work from different phases
* There is no time-limit on this phase. 

Phase 3 - Reflecting on and grading your current understanding

* In Phase 2, you correct your original work. In this phase, you will assess at what level your mastery of the concept is. 
* For each question, you will download and fill out a cover page that allows for you to reflect on your learning and allows you to assign a level for your current understanding. A preview of the cover page can be found [here](https://docs.google.com/document/d/1alQwvwQGEBrTF1COCxG1lQMRUyn1ouacSolwibAditk/){target="_blank"}; you will notice that it has:
    + A reflection box
    + A marking section on completion of the question
    + A correction and grading section 
    + A section about the honor code
* For the questions that you would like to submit for final grading by the instructors, you will upload each one individually to Gradescope this time. Each question will be submitted as a PDF using the same method as in Phase 2, and will be a packet in the following order:
    1. Cover page
    1. Phase 1 attempt with visible corrections (in a radically different color)
* Note that you can submit up to seven questions for final grading. 
* Again, there is no time-limit on this phase. 

Phase 4 Final Grading - This part is done by the instructor team, but we are adding it here so you know what happens after you submit everything. 

* We will look over each solution as well as the corrections and reflections. We will comment on your overall work (including your assessment of your understanding). 
* We then will either affirm your score or adjust if necessary. 


## Logistical practicalities

Here's a quick breakdown of what you need for each phase:

* Phase 1 - 
    + Your brain
    + A laptop (or desktop) download the badge challenge questions onto
    + Blank paper (lined or unlined)
    + A pen or pencil and 2 colored pencils or pens for drawing
    + A device to time your 3-hour window
* Phase 2 - 
    + A device to scan your badge challenge with: a scanner, the CamScanner app on your phone, or some device that can take pictures
    + A laptop (or desktop) to upload your resulting PDF of Phase 1 answers to Moodle, like a computer or laptop
    + A laptop (or desktop) to download the instructor created solutions
    + A radically different colored pen to note your corrections. Note: A blue pen and a black pen are too close. Think blue/black pen vs. red/hot pink level of "radically different" color. 
* Phase 3 - 
    + A laptop (or desktop) to download and edit a cover page for each question
    + The same device as in Phase 2 to scan your paper 
    + A program to create a PDF of the cover page and corrected answer for each question. Depending on what you use, this may be automatically done above. 
    + A laptop (or desktop) to upload each question to Gradescope


## Honor code

Like everything in our course, this new implementation of the badge challenges falls under the purview of Smith's Honor Code. In keeping with Provost Thurston's recommendation to be explicit about the Honor Code as it relates to anything related to assessments, we are listing a few details below:

* You may only use your computer or other computing devices during Phase 1 to look at the list of questions (as if they were a printed copy). Using your computer or computing device for any other purpose during that initial 3-hour period is a violation of the Honor Code. 
* Using any materials beyond blank paper, writing implements, and your own very talented brain is not permitted. Doing so is a violation of the honor code. 
* Giving or receiving a copy of the instructor created solution guide to anyone in this course or anyone outside of this semester's course are violations of the Honor Code. Similarly, uploading anything other than your Phase 1 attempts to Moodle is also a violation of the Honor Code. 
* In Phase 2, you are asked to use one radically different color to mark your corrections. Editing your Phase 1 answers in the same color is a violation of the Honor Code. 
* Discussing the badge challenge with anyone during the window is a violation.

This is a long list of details, and we want to assure you that we are only detailing this list to be clear about exactly how the Honor Code applies. We are seeking to be transparent with expectations under this new system, and we want to underline that we absolutely do trust you. 

We love working at an Honor Code school because we get the privilege of trusting you to act with honor and integrity. Unlike many of our colleagues at other schools, we are not being instructed to use a proctoring service to "police"  students taking assessments at home. For this (among so many other things), we are very, very grateful.  

## FAQ

> Question 1:  I don't like this system. I want to just do the old system. Can I opt to do that?

In short, no. This is the new system for both sections of the course. We understand that this is new and has additional steps for you, but we are doing this for several reasons:

1. Iterative learning process - There is a wealth of education literature that points to the importance of iterating over concepts. You are iterating on the material four times in each self-graded badge challenge: when you (1) study for, (2) attempt, (3) correct, and (4) reflect on each badge challenge. This iteration will make it more likely that you learn the material deeply.
Additionally, with self-corrections, you have nearly instantaneous feedback on your work and your learning. This means that your iterative learning process is quicker and more effective than under the old system. 
1. Equity - We recognize that while education is inherently inequitable,this pandemic is only exacerbating such inequities. While some students have learning spaces where they can take a 3 hour badge challenge without interruption, we know that many are not in such a position. We believe that this system, by adding the correction and reflection phases, effectively downplays the importance of having a 3 hour quiet session. We would rather have an imperfect system that attempts to be more equitable, rather than a system that's only perfect for some.



> Question 2: Under the old system there was no restriction on the number of questions that I could do each time. Why can't I do as many questions as I want? 

Great question! Again, we have several reasons for this restriction:

1. Prior Experience - In our prior experience, we have found that students who study for and attempt more than 7 questions tend to not be as successful in demonstrating their mastery of the concepts as they stretch themselves too thin. This may be in part that they are studying too many things and as such, can not deeply study each concept. It also could be due to the limited time during the actual sitting of the badge challenge. Regardless of the reason, we have noticed that in the case of badge challenges attempting more is generally less (in terms of scores). 
1. Engaging the Badge Challenge System - Given our prior experience and that with the current remote learning set-up, we want to more plainly help you strategize for the badge challenges. By knowing in advance that seven is the most number of badges you can get "credit" for, we hope that you will more directly engage with the "chart your own learning journey" part of this system.
1. Your well-being - Under this new implementation, you will be engaging with each question 4 times (by studying, attempting questions, marking corrections, and then reflecting). So in addition to guiding your educational journey, we want to help you guard your physical time as well as your well-being. Additionally,  this limit downplays the need for a perfectly quiet 3 hour badge challenge session. 


> Question 3: Following up on the above question, what if I turn in 8 questions anyways? 

We will only give you credit for the first seven that you hand in. 

> Question 4: With this seven question restriction, how is it possible to be able to redo badges? 

We have three more badge challenges, which means that if you do 7 badges each time that is 21 badge attempts, and that number does not include any of the badges that you did one the first one. This means that not including anything from the first badge challenge, you can attempt each one once and 6 of them twice. 

> Question 5: I'm super worried about my grade under this model. 

First, remember that this course (along with every course at Smith) is mandatory S/U. To earn a passing grade just for the badge challenges means earning 32/45 points for that section of your grade. That means doing at least 12 badges, earning 3 Golds, 5 Silvers, and 4 Bronzes. If this is your goal, not counting anything on your first badge challenge, you would need to do 4 badges on each of the remaining badge challenges. 

> Question 6: How will my reflections be graded?

Your reflections are part of the instructors' final assessment of your mastery. Below are a few examples: 

1. If your reflection is "I'm awesome and got everything right on this question" but then we see that there is an important difference between your Phase 1 solution and the instructor-provided solutions , then we will note the difference and likely adjust your self-given grade. 
1. Similarly, for example - If your reflection is "I wrote the same thing the instructors always say, so I know I've mastered this topic because", we will likely reflect back to you that your original wording is just repeating our wording and this is not in fact a demonstration of mastering a concept. In this case, we will also likely adjust your self-given grade. A more thorough reflection in this situation could include, for example, a reflection on how you identified the correct concepts to apply in your answer.
1. In contrast to the two above, being overly harsh on your work in your reflection will also merit a comment. If we believe that you have clearly mastered a concept but your reflection does not seem to share that belief, we will comment on that discrepancy as well. 



***



# Badge Challenge II {#challengeII}

## Administrative notes

* Time window: **Friday 4/10 12:01am through Wednesday 4/15 11:59pm**
    + You can start the badge challenge after Friday 4/10 12:01am Eastern Daylight Time
    + You must submit your badge challenge before Wednesday 4/15 11:59pm Eastern Daylight Time
* Format: We will post the format and submission method for this badge challenge at the same time as Lec24 on the evening of Thursday 4/2. **We will decide on the format based on your responses to the survey posted in the "COVID-19" tab of the webpage above, which are due Tuesday 3/31 at 11pm Eastern Daylight Time.**
   
    
<!--    
* In preparation for badge challenge:
    + Designate a 3 hour window that you can dedicate to completing this badge challenge.
    + Have the following ready: colored pencils/pens, blank sheets of paper, your laptop, and a mobile phone with a camera.
    + If you haven't already, all Office of Disability Services forms must be submitted to instructor before the start of the time window.
* "Printing the badge challenge":
    + Instead of printing a timestamped copy of the badge challenge as you would in Seelye, you will click a link on Moodle to "start" the exam. We will use Moodle's internal timestamp logs to determine when you "started" your badge challenge
    + You do not need to physically "print" the badge challenges.
* "Completing the badge challenge":
    + You will write you answers down on your blank sheets of paper.
    + Remember that you only have to do as many questions as you are ready for. If a question has multiple parts, you **must** attempt all parts to earn above *X* (cannot be assessed).
* "Submitting the badge challenge":
    + You will submit your badge challenge on Gradescope as you would for a problem set. We will use the Gradescope submission timestamp to determine when you "submitted" your badge challenge.
* Honor code:
    + Closed-book, no internet, and individually completed. You may only use your laptop to view the badge challenge
    + You will be given 3 hours to complete it. **Timestamps will be strictly enforced. Any badge challenges with pairs of timestamps indicating that more time than allowed was taken will be subject to an honor board case.**
    + You are prohibited from discussing the badge challenge with your peers during the time window. 
-->


## Badges 1-10
    
* Badges: Lectures 1-24 & problem sets 1-7.  In other words everything up to resampling and not confidence intervals.
* What to study:
    + Badge challenge 1!
    + Your hand-written course notes first: they are the "executive summaries" of topics.
    + The material on the course webpage chronologically, in particular the ModernDive readings.



***



# Badge Challenge III {#challengeIII}

## Administrative notes

* Time window: **Friday 4/24 12:01am through Wednesday 4/29 11:59pm**
    + You can start the badge challenge after Friday 4/24 12:01am Eastern Daylight Time
    + You must submit your badge challenge before Wednesday 4/29 11:59pm Eastern Daylight Time
* Format: TBD
* We will have badge challenge III graded and returned to you by the evening of Saturday 5/2 so that you can study it for badge challenge IV.



## Badges 1-15
    
* Badges: All Lectures 1-35 & all problem sets 1-9. In other words everything.
* What to study:
    + Badge challenges 1 and 2!
    + Your hand-written course notes: they are the "executive summaries" of topics.
    + The material on the course webpage chronologically, in particular the ModernDive readings.



***



# Badge Challenge IV {#challengeIV}

## Administrative notes

* Time window: **Exam week: Monday 5/4 12:01am through Friday 5/8 11:59pm**
    + You can start the badge challenge after Monday 5/4 12:01am Eastern Daylight Time
    + You must submit your badge challenge before Friday 5/8 11:59pm Eastern Daylight Time
* Format: TBD

## Badges 1-15
    
* Badges: All Lectures 1-35 & all problem sets 1-9. In other words everything.
* What to study:
    + Badge challenges 1, 2, and 3!
    + Your hand-written course notes: they are the "executive summaries" of topics.
    + The material on the course webpage chronologically, in particular the ModernDive readings.

