---
title: "SDS/MTH 220: Intro to Probability and Statistics"
author: "Sec01: Albert Y. Kim & David Rockoff. Sec02: Katherine Kinnaird & Will Hopper"
date: "Last updated on `r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
    includes:
      in_header: "favicon.html"
---

<style>
h1{font-weight: 400;}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=TRUE, 
  message=FALSE, 
  warning=FALSE, 
  eval=FALSE, 
  fig.width=16/2, 
  fig.height=9/2
)
library(tidyverse)
library(stringr)
library(knitr)
library(lubridate)
library(forcats)
library(fivethirtyeight)
library(nycflights13)
library(gapminder)
library(babynames)
library(scales)
library(moderndive)
library(here)
library(kableExtra)
# devtools::install_github("hadley/emo")
library(emo)
library(patchwork)

# Set seed value of random number generator to get "replicable" random numbers.
set.seed(76)
```



***



# Schedule 

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQM-5FVt5BKJZsfElEV19NwD2MXGgSVUfGLB7dUoD0MbCU6Dkzqx66UMxbgqMaiS6H8CP8numV5Xaf-/pubhtml?gid=346882447&amp;single=true&amp;widget=true&amp;headers=false" width="100%" height="1015"></iframe>

<!--
{target="_blank"}
-->



***



# Lec 03: Fri 1/31

## Annoucements


## Chalk talk

1. Draw histogram by hand, emphasizing that bins correspond to intervals (right-edge inclusive).
1. Adjust the binning structure of the previous hand-drawn histogram two ways:
    + Adjusting the binwidth
    + Adjusting the number of bins
1. Facets split one graphic by the values of another variable (that does not have too many unique values).



***



# Lec 02: Wed 1/29

## Annoucements

1. Fatima Keita is interested in organizing a group for students of color within SDS, called SDS coalition of color (SDSCC). She has also put together a survey to gather students of color's experiences within SDS courses and the program more generally. If you identify as a student of color and you've taken at least one SDS course, please take a moment to complete Fatima's [SDSCC Preliminary Interest Survey](https://www.surveymonkey.com/r/2YZ785Y){target="_blank"}. The idea is that these experiences would then be anonymously shared with the SDS faculty in hopes that we can work to improve inclusivity within the program and curriculum. If you are interested in joining, please email Fatima directly.
1. In-class demo of Gradescope.
1. This week's problem set has three elements
    + Submit PDF on Gradescope with questions tagged
    + Fill out Intro Survey Google Form
    + Submit on Moodle reflection piece which builds off in-class reflection exercise.
    
    
## Chalk Talk

1. Draw scatterplot by hand
1. Define of Grammar of Graphics
1. Write example `ggplot()` code
1. Explain what jittering does to graphic and what it does not do to original data



***



# Lec 1: Mon 1/27

## Announcements

* Introductions
* If you're having registration issues:
    + Please keep in mind that SDS201 is a course that also satisfies the intro stats pre-requisite for many majors, including PSY, GOV, BIO, NSC, ENV, and SDS. Please consider that option as it currently has lots of room.
    + If you are not registered for this course, fill out the waitlist [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdDfcVmrz8p2rmS2BXqT6tv3a-Syzn2gmIG88h4CYQzRvKltw/viewform){target="_blank"} before Thursday 5pm.
    + We will start informing students and signing green slips on Friday afternoon.
    + If you have previously put your name on the above waitlist Google Form but no longer need a spot, we would very much appreciate a message letting us know. This will help us and your peers a lot.
* Syllabus 
    + Honor code discussions
    + Reflection exercise
    
    
## Lecture

Here is the typical lecture flow:

* Start with a 10-15 minute "chalk talk". We do this to motivate the day's topics and warn you about potential pitfalls in understanding
* Followed by in-class ModernDive readings listed in the above schedule. We do this so you can read at your own pace, talk to your peers, and ask us questions. While you do not need to submit your "Learning Check" answers, we *highly* recommend you write them down and verify your answers in Appendix D of ModernDive.

Today's topics:

* Introduction to Slack: A brief demo
* Introduction to R, RStudio, and R packages: ModernDive readings
