---
title: "Midterms"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: yes
---

<style>
h1{font-weight: 400;}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=TRUE, 
  message=FALSE, 
  warning=FALSE, 
  eval=FALSE, 
  fig.width=16/2, 
  fig.height=9/2
)
# tidyverse R packages:
library(ggplot2)
library(dplyr)
library(tibble)
library(tidyr)
library(readr)
library(purrr)
library(forcats)
library(stringr)
library(lubridate)
library(forcats)
library(gapminder)
library(patchwork)
```

<!--
{target="_blank"}
-->

***



# Midterm format

1. Format is based on Marney Pratt's [BIO 131](https://docs.google.com/document/d/1_FB2EHtqTEpd1RJHb6SfyV19rgXlrjNKbsxhPh9UC6w/edit){target="_blank"}. Differences are:
    a) Replace Marney's table of 12 standards with our 15 [learning goals](https://docs.google.com/spreadsheets/d/e/2PACX-1vQM-5FVt5BKJZsfElEV19NwD2MXGgSVUfGLB7dUoD0MbCU6Dkzqx66UMxbgqMaiS6H8CP8numV5Xaf-/pubhtml?gid=323806801&single=true)
    a) Marney's weights for each standard at the end do not apply. In our case all 15 learning goals are weighted equally
1. The exam periods are in the McConnell Hall Foyer Friday 3:00-9:00 pm, Saturday 12:00-6:00 pm, and Sunday 12:00-6:00 pm.
1. Read the "Basics" and "For Students" sections of the **new** [Spring 2022 Self Scheduled Exams instructions](https://www.science.smith.edu/self-scheduled-exam-printing/){target="_blank"}
1. You are all subject to the [Smith Honor Code](https://www.smith.edu/about-smith/offices/student-affairs/student-handbook/academic-honor-code-0#:~:text=Honor%20Code%20Statement&text=Smith%20College%20expects%20all%20students,of%20course%20work%20and%20examinations.){target="_blank"}
1. Notes for before exam:
    + Bring 3 colored pencils/pens.
    + Bring your Smith ID card
    + You do not need a calculator.
1. Notes for during exam:
    + Closed-book, no internet, and individually completed.
    + In case of potential errors or ambiguity on the exam, please note them, state your assumptions, and use your best judgement.
    + Timestamps will be strictly enforced. Any timestamps indicating than more time was taken than allowed are subject to an honor board case. Those with ODS accommodations have the extended time specified in their ODS documentation letter. 




***



# Midterm I {#midtermI}

## Administrative notes

1. Friday 3/4 through Sunday 3/6. See times above
1. You will be given 120 mins to complete it (including transit time to writing areas), however I try to time it so that it will take much less than that. In other words, you should have plenty of time to complete it without rushing.
1. You are allowed a single 3x5 inch index card of notes (double-sided ok). You are required to submit your index card with your midterm, which you will then get returned to you. 


## What to Study

1. Everything relating to [learning goals](https://docs.google.com/spreadsheets/d/e/2PACX-1vQM-5FVt5BKJZsfElEV19NwD2MXGgSVUfGLB7dUoD0MbCU6Dkzqx66UMxbgqMaiS6H8CP8numV5Xaf-/pubhtml?gid=323806801&single=true) 1-5:
    1. Lecture chalk talks
    1. Labs/problem sets (PS05 solutions will be posted after all PS05's have been submitted)
    1. Book readings
1. You don't need to write complete and perfectly function code, however you might need to
    1. Understand presented code
    1. Fill in the blanks
    1. Write pseudocode (learning goal 2). See below:

    
## What is "pseudocode"?

Think of pseudocode as a recipe, blue print, or algorithm outline that balances:

1. Being *just specific enough* that someone who reads it can walk through the steps unambiguously
1. But *not being so specific* that it has to work perfectly when typed into R



***



<!--
https://docs.google.com/document/d/1tHFupDpC1ZeoTeJAOk4_D0uAatG9n19nmmUGkrH6y7w/edit
-->


<!--

*Posted Saturday, April 4th, 2020* In this new phase of the course, we are adjusting the format for badge challenges II, III, and IV to follow a **self-graded** model. This model is used by certain members of Smith's Engineering Department and this semester is being expanded in some engineering classes to their exams. 

## Motivation

As stated on our COVID-19 Information document, our overarching theme for the rest of the semester is both **Maximal Flexibility** and **Equity**. The world has changed, and your learning spaces and environments have changed drastically. We believe that employing a version of self-graded badge challenges provides  for 1) greater flexibility than trying to "proceed as normal" and 2) more equity across variations in living situations and learning environments. All this while still retaining the badge challenge system's core philosophy of "mastery-based learning."


## Video summaries {#videos}

*Posted Tuesday, April 7th, 2020* 

For a summary on "How to Take Badge Challenge 2", watch this 5m20s YouTube video. This video is a visual summary of the "Process", "Logistics", and "Honor Code" sections below. 

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/l6IJSJ9V_c4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>
</br>

For a summary on "How to Study for Badge Challenge 2", watch this 14m10s YouTube video.

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/bwG0LmgOgOg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>
</br>


## Process

First and foremost, yes, there are still badge challenges.

* There are still badge challenge "windows", but they are longer than the Seelye self-scheduled window we had for badge challenge 1. 
* The maximum number of badges that you can turn in at the end of the Phase 3 is 7. After describing the process, there is a FAQ section where we will justify the reasoning behind our decisions. 

However, the steps you'll follow to complete a badge challenge is now a new three stage process. Below lists how this will work: 

**Phase 1:** Initial solutions for badge challenge questions

* This phase resembles the "usual" model where you will have 3h (instead of 2h20min) from the time you download the badge challenge from Moodle and when you stop working. 
* You are not required to print the badge challenge. Rather, you only need to download it onto a device to view it. 
* Just as with Badge Challenge 1, you are completing the badge challenge on paper without the aid of:
    1. A computing device, except to view the badge challenge questions
    1. Your class notes
    1. The textbook 
    1. Of speaking to anyone else about the badge challenge during the window.
* In this phase, each question should be written on its own page. In other words, do not try to squeeze two questions or parts of two questions onto the same physical page. 
* In this phase, only the questions that you attempt "move on" to Phase 2 . 

**Phase 2:** Checking your Phase 1 responses

* In this phase, you will upload a PDF your Phase 1 on **Moodle** and then automatically get access to the instructor-created solution guide. 
* To create a PDF of all of your answers to submit, we recommend using either:
    1. A scanner if you have access to one 
    1. The [CamScanner App](https://www.camscanner.com/user/download){target="_blank"} on a smartphone
    1. Creating photos using some camera and then converting these photos to PDF
* Note that the time to scan and upload your file is NOT part of your 3h Phase 1 window. 
* Once you have the instructor-created solutions, you will correct your Phase 1 work in a **different color ink**.  Please choose colors that are radically different from each other so that we can easily distinguish work from different phases.
* There is no time-limit on this phase. 

**Phase 3:** Reflecting on and grading your current understanding

* In Phase 2, you correct your original work. In this phase, you will assess at what level your mastery of each concept is. 
* For each question, you will download and fill out a cover page that allows for you to reflect on your learning and allows you to assign a level for your current understanding. A preview of the cover page can be found [here](https://docs.google.com/document/d/1alQwvwQGEBrTF1COCxG1lQMRUyn1ouacSolwibAditk/){target="_blank"}; you will notice that it has:
    + A reflection box
    + A marking section on completion of the question
    + A correction and grading section 
    + A section about the honor code
* For the questions that you would like to submit for final grading by the instructors, you will upload each one individually to **Gradescope** this time. Each question will be submitted as a PDF created using the same method as in Phase 2, and will be a packet in the following order:
    1. Cover page
    1. Phase 1 attempt with visible corrections (in a radically different color)
* Note that you can submit up to **seven** questions for final grading. 
* Again, there is no time-limit on this phase. 

**Final Grading:** This part is done by the instructor team, but we are adding it here so you know what happens after you submit everything. 

* We will look over each solution as well as the corrections and reflections. We will comment on your overall work, including your assessment of your understanding. 
* We then will either affirm your score or adjust if necessary. 


## Logistics

Here's a quick breakdown of what you need for each phase:

**Phase 1:** Initial solutions for badge challenge questions

+ Your brain
+ A laptop (or desktop) to download the badge challenge questions onto
+ Blank paper (lined or unlined)
+ A pen or pencil and 2 colored pencils or pens for drawing
+ A device to time your 3-hour window

**Phase 2:** Checking your Phase 1 responses

+ A device to scan your badge challenge with: a scanner, the CamScanner app on your phone, or some device that can take pictures
+ A laptop (or desktop) to both
    1. Upload your resulting PDF of Phase 1 answers to Moodle, like a computer or laptop
    1. Download the instructor-created solution guide
+ A radically different colored pen to note your corrections. Note: A blue pen and a black pen are too close. Think blue/black pen vs. red/hot pink level of "radically different" color. 

**Phase 3:** Reflecting on and grading your current understanding

+ A laptop (or desktop) to download and edit a cover page for each question
+ The same device as in Phase 2 to scan your paper 
+ A program to create a PDF of the cover page and corrected answers for each question. Depending on what you use, this may be automatically done above. 
+ A laptop (or desktop) to upload each question to Gradescope


## Honor code

Like everything in our course, this new implementation of the badge challenges falls under the purview of Smith's Honor Code. In keeping with Provost Thurston's recommendation to be explicit about the Honor Code as it relates to anything related to assessments, we are listing a few details below:

* You may only use your computer or other computing devices during Phase 1 to look at the list of questions (as if they were a printed copy). Using your computer or computing device for any other purpose during that initial 3-hour period is a violation of the Honor Code. 
* Using any materials beyond blank paper, writing implements, and your own very talented brain is not permitted. Doing so is a violation of the honor code. 
* Giving or receiving a copy of the instructor created solution guide to anyone in this course or anyone outside of this semester's course are violations of the Honor Code. Similarly, uploading anything other than your Phase 1 attempts to Moodle is also a violation of the Honor Code. 
* In Phase 2, you are asked to use one radically different color to mark your corrections. Editing your Phase 1 answers in the same color is a violation of the Honor Code. 
* Discussing the badge challenge with anyone during the window is a violation.

This is a long list of details, and we want to assure you that we are only detailing this list to be clear about exactly how the Honor Code applies. We are seeking to be transparent with expectations under this new system, and we want to underline that we absolutely do trust you. 

We love working at an Honor Code school because we get the privilege of trusting you to act with honor and integrity. Unlike many of our colleagues at other schools, we are not being instructed to use a proctoring service to "police"  students taking assessments at home. For this (among so many other things), we are very, very grateful.  

## FAQ

> Question 1:  I don't like this system. I want to just do the old system. Can I opt to do that?

In short, no. This is the new system for both sections of the course. We understand that this is new and has additional steps for you, but we are doing this for several reasons:

1. *Iterative learning process*: There is a wealth of education literature that points to the importance of iterating over concepts. You are iterating on the material four times in each self-graded badge challenge: when you (1) study for, (2) attempt, (3) correct, and (4) reflect on each badge challenge. This iteration will make it more likely that you learn the material deeply.
Additionally, with self-corrections, you have nearly instantaneous feedback on your work and your learning. This means that your iterative learning process is quicker and more effective than under the old system. 
1. *Equity*: We recognize that while education is inherently inequitable,this pandemic is only exacerbating such inequities. While some students have learning spaces where they can take a 3 hour badge challenge without interruption, we know that many are not in such a position. We believe that this system, by adding the correction and reflection phases, effectively downplays the importance of having a 3 hour quiet session. We would rather have an imperfect system that attempts to be more equitable, rather than a system that's only perfect for some.



> Question 2: Under the old system there was no restriction on the number of questions that I could do each time. Why can't I do as many questions as I want? 

Great question! Again, we have several reasons for this restriction:

1. *Prior Experience*: In our prior experience, we have found that students who study for and attempt more than 7 questions tend to not be as successful in demonstrating their mastery of the concepts as they stretch themselves too thin. This may be in part that they are studying too many things and as such, can not deeply study each concept. It also could be due to the limited time during the actual sitting of the badge challenge. Regardless of the reason, we have noticed that in the case of badge challenges attempting more is generally less (in terms of scores). 
1. *Engaging the Badge Challenge System*: Given our prior experience and that with the current remote learning set-up, we want to more plainly help you strategize for the badge challenges. By knowing in advance that seven is the most number of badges you can get "credit" for, we hope that you will more directly engage with the "chart your own learning journey" part of this system.
1. *Your well-being*: Under this new implementation, you will be engaging with each question 4 times (by studying, attempting questions, marking corrections, and then reflecting). So in addition to guiding your educational journey, we want to help you guard your physical time as well as your well-being. Additionally,  this limit downplays the need for a perfectly quiet 3 hour badge challenge session. 

> Question 3: Following up on the above question, what if I turn in 8 questions anyways? 

We will only give you credit for the first seven that you hand in. 

> Question 4: With this seven question restriction, how is it possible to be able to redo badges? 

We have three more badge challenges, which means that if you do 7 badges each time that is 21 badge attempts, and that number does not include any of the badges that you did one the first one. This means that not including anything from the first badge challenge, you can attempt each one once and 6 of them twice. 

> Question 5: I'm super worried about my grade under this model. 

First, remember that this course (along with every course at Smith) is mandatory S/U. To earn a passing grade just for the badge challenges means earning 32/45 points for that section of your grade. That means doing at least 12 badges, earning 3 Golds, 5 Silvers, and 4 Bronzes. If this is your goal, not counting anything on your first badge challenge, you would need to do 4 badges on each of the remaining badge challenges. 

> Question 6: How will my reflections be graded?

Your reflections are part of the instructors' final assessment of your mastery. Below are a few examples: 

1. If your reflection is "I'm awesome and got everything right on this question" but then we see that there is an important difference between your Phase 1 solution and the instructor-provided solutions , then we will note the difference and likely adjust your self-given grade. 
1. Similarly, for example - If your reflection is "I wrote the same thing the instructors always say, so I know I've mastered this topic because", we will likely reflect back to you that your original wording is just repeating our wording and this is not in fact a demonstration of mastering a concept. In this case, we will also likely adjust your self-given grade. A more thorough reflection in this situation could include, for example, a reflection on how you identified the correct concepts to apply in your answer.
1. In contrast to the two above, being overly harsh on your work in your reflection will also merit a comment. If we believe that you have clearly mastered a concept but your reflection does not seem to share that belief, we will comment on that discrepancy as well. 



***



# Badge Challenge II {#challengeII}

## Administrative notes

* Time window: **Friday 4/10 12:01am through Wednesday 4/15 11:59pm**
    + You can start the badge challenge after Friday 4/10 12:01am Eastern Daylight Time
    + You must submit your badge challenge before Wednesday 4/15 11:59pm Eastern Daylight Time
* Format: See the [Revised Format](#challenge-format) section above.
* Please note that Badges 9, 10, and 11 were rebalanced for clarity as follows:
    + The current Badge 11 used to be two separate badges. We felt the distinction was unclear and hence merged them.
    + We added the current Badge 9 on the Central Limit Theorem to emphasize its importance in statistical inference.


## Badges 1-10
    
* Badges: Lectures 1-24 & problem sets 1-7.  In other words everything up to resampling and not confidence intervals.
* What to study:
    + Badge challenge 1!
    + Your hand-written course notes first: they are the "executive summaries" of topics.
    + The material on the course webpage chronologically, in particular the ModernDive readings.



***



# Badge Challenge III {#challengeIII}

## Administrative notes

* Time window: **Friday 4/24 12:01am through Wednesday 4/29 11:59pm**
    + You can start the badge challenge after Friday 4/24 12:01am Eastern Daylight Time
    + You must submit your badge challenge before Wednesday 4/29 11:59pm Eastern Daylight Time
* Format: See the [Revised Format](#challenge-format) section above.
* We will have badge challenge III graded and returned to you by the evening of Saturday 5/2 so that you can study it for badge challenge IV.



## Badges 1-15
    
* Badges: All Lectures 1-35 & all problem sets 1-9. In other words everything.
* What to study:
    + Badge challenges 1 and 2!
    + Your hand-written course notes: they are the "executive summaries" of topics.
    + The material on the course webpage chronologically, in particular the ModernDive readings.



***



# Badge Challenge IV {#challengeIV}

## Administrative notes

* Time window: **Exam week: Monday 5/4 12:01am through Friday 5/8 11:59pm**
    + You can start the badge challenge after Monday 5/4 12:01am Eastern Daylight Time
    + You must submit your badge challenge before Friday 5/8 11:59pm Eastern Daylight Time
* Format: See the [Revised Format](#challenge-format) section above.

## Badges 1-15
    
* Badges: All Lectures 1-35 & all problem sets 1-9. In other words everything.
* What to study:
    + Badge challenges 1, 2, and 3!
    + Your hand-written course notes: they are the "executive summaries" of topics.
    + The material on the course webpage chronologically, in particular the ModernDive readings.

-->
