---
title: "Syllabus"
output:
  html_document:
    toc: yes
    toc_depth: 1
    toc_float:
      collapsed: no
---

<!--
{target="_blank"}
-->

<style>
h1{font-weight: 400;}
</style>

# Revised: Basic information {#basicinfo}

* **Course title:** SDS/MTH 220: Introduction to Probability and Statistics
* **Communication**: All communication will take place via Slack.
    + You must have the Slack Desktop or Mobile App installed; it's too easy to miss messages when using the browser version. You can download them [here](https://slack.com/downloads/){target="_blank"}.
    + After you've installed Slack, add the sds-mth-220-2020-01.slack.com workspace.
* **Lectures:**
    + Monday lectures will be posted on the course webpage by Sunday night.
    + Wednesday lectures will be posted on the course webpage by Tuesday night.
    + Friday lectures will be posted on the course webpage by Thursday night.
* **Getting help**:
    + Ask questions in the `#questions` channel on Slack.
    + Check the Zoom discussion sessions [Google Calendar](https://calendar.google.com/calendar/embed?src=smith.edu_qd5sufjufbms2430ielqeego24%40group.calendar.google.com&ctz=America%2FToronto){target="_blank"}.
    + Schedule one-on-one appointments with a Spinelli Tutor. Instructions will be posted here shortly.
    + Schedule one-on-one appointments with the instructors or lab instructors using the instructions on [Moodle](https://moodle.smith.edu/course/view.php?id=37125){target="_blank"}. In the interest of keeping everyone in the loop, we ask as much as possible to limit these appointments to private/individual concerns.


## Instructor work-life balance

* We will respond to Slack messages sent during the week within 24h. We will respond to Slack messages sent during the weekend at our own discretion.
* If possible, please only Slack us with briefer and administrative questions; we prefer having more substantive conversations over Zoom as it takes us less energy to understand where you are at.
* We will do our best to return all grading as promptly as possible.



***



# How can I succeed in this class? {#succeed}

Borrowing language from the 2019 Google J-term course here at Smith, when learning in a classroom setting, at any moment, we exist in one of three zones: *safe, stretch,* or *strain.*    

* A student in the *safe* zone is completely comfortable, and the course material is completely within what the student already knows.    
* The *strain* zone is the complete opposite of the safe zone. A student in the *strain* zone feels completely overwhelmed with the material to the point where they can’t find any meaningful connections between the current material and what the student already knows. 

The material in this course challenges our understanding of statistics and probability. Several of the topics are subtle and require iterative engagement. The goal for this course is to spend the vast majority of our time in the *stretch* zone. In this zone, the material is just beyond our current knowledge base and while we are a bit uncomfortable with the material, we can see possible paths to tie the new material into our existing knowledge. In other words, in this class, our brains should be *stretching*, but not *straining*. 

At the end of each week, if you have not been surprised or challenged, or if you have no questions about the material, this could mean that you are in the safe or strain zones. If you find yourself exasperated or negative about the class, you may be in the strain zone. If you find yourself using words like “boring” or “easy”, you are likely in the safe zone. If you are in either zone, please come to office hours, make an appointment, or send us a slack. We want you to get the most out of this course, but we cannot help you if we do not have firsthand knowledge of what is going on. 

The strain zone is never a fun place to be during a class. As you work to return to the stretch zone, you might consider the following questions: 

* **When I have questions or don't understand something:**
    + *"Am I asking questions in class?"*
    + *"Am I asking questions on Slack in `#questions`?"* Even better: *"Am I answering my peers' questions on Slack?"*
    + *"Having I been going to the Spinelli tutoring center?"*
    + *"Have I been coming to office hours?"*
* **Lectures, labs, and readings:**
    + *"Am I completing all the ModernDive readings/in-class activities for a given lecture before the start of the next lecture?"*
    + *"Am I staying on top Slack notifications sent between lectures?"* If you need help developing a notification strategy that best suits your lifestyle, please speak to us. 
    + *"Am I attending lectures consistently?"*
    + *"Am I actually running the code and studying the outputs in R during in-class exercises, or am I just skimming the text?"*
    + *"During in-class exercises and lab time, am I taking full advantage that I'm in the same place at the same time with the instructor, the lab assistants, and most importantly your peers, or am I browsing the web/texting the whole time?"*
* **Problem sets and coding:**
    + *"Am I actually doing the problem sets?"*
    + *"When learning to code, much like learning a language, have I been really pushing myself to practice, practice, practice?"*


## A note on pre-requisites

While the course does have a calculus pre-requisite, having experience with calculus and/or statistics does not guarantee you success in this course, nor does having no experience mean that you are not set-up to succeed in this course. Success in this course will be determined by a student’s willingness to ask questions, grapple with challenging concepts, and to persistently take small meaningful steps towards deeper understanding and facility with the concepts. 



***



# Course Description & Objectives

* **Official course description**: On [Smith College
Course Search](https://www.smith.edu/academics/academic-program/curriculum/course-search?term=Spring+2019&dept=&instr=Albert+Y.+Kim&credits=&course_numb=220&course_keywd=&op=Submit&form_build_id=form-denY7g_Jg58ti6JEd7MQqOj4CvHwIw6awhXG9B0jLHs&form_id=campus_course_search_basic_search_form){target="_blank"}.
* **Objectives**: This semester you will
    1. Learn statistical inference via data science, not mathematics/probability theory.
    1. Engage in the [data/science research pipeline](project.html) in as faithful a manner as possible while maintaining a level suitable for novices.
    1. Develop your statistical literacy, a necessary ability for effective citizenship.



***



# Topic Schedule and Readings {#topicschedule}

A rough topic schedule and corresponding readings are posted below on the [main page](index.html) of this course webpage. We will draw from the following sources:

1. [Statistical Inference via Data Science: A moderndive into R and the tidyverse](https://moderndive-bert.netlify.com/){target="_blank"}. We'll be using the development version; click link in menubar above. Follow the book on Twitter [\@ModernDive](https://twitter.com/ModernDive){target="_blank"}.
1. [OpenIntro: Introductory Statistics with Randomization and Simulation](https://www.openintro.org/stat/textbook.php?stat_book=isrs/){target="_blank"} by Diez, Barr, and Cetinkaya-Rundel
    + Free [PDF](https://www.openintro.org/download.php?file=isrs1_tablet&referrer=/stat/textbook.php){target="_blank"}
    + Hardcopy. Available on [Amazon](https://www.amazon.com/Introductory-Statistics-Randomization-Simulation-David/dp/1500576697/ref=pd_sbs_14_2?_encoding=UTF8&pd_rd_i=1500576697&pd_rd_r=8a25adfe-b61a-11e8-8e51-357518f34f72&pd_rd_w=SqIFV&pd_rd_wg=mb7dk&pf_rd_i=desktop-dp-sims&pf_rd_m=ATVPDKIKX0DER&pf_rd_p=53dead45-2b3d-4b73-bafb-fe26a7f14aac&pf_rd_r=83CCQTHW3KV5NTNHT22J&pf_rd_s=desktop-dp-sims&pf_rd_t=40701&psc=1&refRID=83CCQTHW3KV5NTNHT22J){target="_blank"}
    


***  



# Revised: Evaluation {#evaluation}

## Weekly Problem Sets 15%

*Revised: The only change for problem sets are the due dates. See the course schedule posted on the [main page](index.html) of this course webpage.*

* Total of 9 problem sets.
* Each full problem set is worth 100 pts and each "lite" problem set is worth 50 pts. So there are total of 750 possible pts, however the final computation will be out of **600 pts**. In other words, you have a 750 - 600 = 150 point cushion.
* This means that you can decide to not hand in at least one full problem set any reason. It could be because you are ill, you forgot about the assignment, or you had too much work for your other courses. *Note that pre-planned “dropping” of labs should be used sparingly because we can not predict when life will happen (ie. illness, etc).* Alternatively, you could hand in all the problem sets and allow for smaller mistakes on each one to effectively be "waved."
* The problem sets in this class should be viewed as low-stakes opportunities to
practice, instead of evaluative tools used by the instructor to assign grades.
**Each problem set is worth less than 2% of your final grade**.

## Term Project 30% {#termproject}

*Revised: The third and fourth phases of the term project have been revised significantly. See the [Term Project](term_project.html) page for more details.*

See [Term Project](term_project.html) page. While your term project grade is only based on your final resubmission, your level of contributions at all the intermediate steps (data, proposal, and initial submission) will affect your engagement grade; see [Engagement](#engagement) below.

## Badge Challenges: 45%

*Revised: While the mechanics of taking/submitting the badge challenges have changed since we no longer have access to Seelye self-scheduled exams, the "mastery-based grading" philosophy of our badge challenges will remain the same. See the [Badge Challenges](badge_challenges.html) page for more details.*

See [Badge Challenges](badge_challenges.html) page. Note that is possible to satisfy all 15 badges in the first three badge challenges, making the 4th badge challenge an opportunity to revise and improve your grade.

## Engagement 10% {#engagement}

Being part of a professional community has many parts; we generate and 
consume knowledge, we review and critique work, and we present to and 
learn from each other. The edge of what we know is constantly being pushed
further and further as we discover new ideas, create new knowledge, and 
ask new questions. At times, we are computers, writers, and contractors, 
and then at other times, we serve as reviewers, mentors, and learners. The 
constancy is our willingness to be present and active within our professional 
community. With this in mind, in this course, your participation is expected, 
especially **you'll only get out of this class as much as you put in**. That 
being said, here are multiple pathways for you to stay engaged in this class: [Google Doc](https://docs.google.com/document/d/14PBmTU_wBTEI8j1lqZWFqFI3ETAD6N5qao-2ADQRTTM/edit){target="_blank"}.

Participation can take many forms, including but not limited to: attending 
class meetings, being active on our course slack, participating in discussion 
in class, offering ideas and questions in class or on slack. Beyond attending 
class, our class as a community will generate a list of what we believe are 
ways to engage and participate in our course. Adding to this list one way 
that you are called to participate in this course. If you find yourself unwilling 
or resistant to adding to this list, examine this. *What is holding you back?* 
*What would help propel you to action?*

The engagement part of the course will be graded with student input. In the week 
before spring break and during the last week of classes, you will be asked to 
complete a self-evaluation of your class engagement in context of the class 
engagement list. Your self-evaluations will be a critical part of determining 
this section of your grade, but not the only determining factor. 



## Policies

1. **Collaboration**: While we encourage you to work with your peers for problem
sets and labs, you must submit your own answers and not simple rewordings of
another's work. Furthermore, all collaborations must be explicitly acknowledged
in your submissions.
1. **Problem sets**:
    + No extensions will be granted without a dean's note.
    + To receive full credit, you must show your work and explain your reasoning in your solutions. 
    + Revised: All written problem sets must be handed in ~~by 9am on Mondays~~ at the appropriate due time on Gradescope. No emailed submissions will be accepted.
1. **Engagement**:
    + There are 4 reflective assignments for the course: 2 reflective writing assignments and the 2 self-evaluation forms. You should complete 3 of the four assignments. 
1. **Badge Challenges**:
    + No make-up badge challenges will be allowed without a dean's note. 
    + Timestamps for all midterms will be strictly enforced.
1. **Grading**: We reserve the right to not discuss any grading issues in class and instead direct you to office hours or after class. 



***



# Academic Integrity

## Honor Code Principles

Being at a school with an Honor Code, like Smith, is a special privilege. 
The Honor Code goes beyond inviting students to act with integrity, instead 
it welcomes students as equal participants of the learning community, 
imbuing students with the same level of trust that we extend to our 
collaborators and colleagues. The Smith College Honor Code, established 
in 1944, and as stated in the Student Handbook, says:

> Smith College expects all students to be honest and committed to the 
> principles of academic and intellectual integrity in their preparation 
> and submission of course work and examinations. Students and faculty at 
> Smith are part of an academic community defined by its commitment to 
> scholarship, which depends on scrupulous and attentive acknowledgement 
> of all sources of information, and honest and respectful use of college 
> resources.

This trust bestowed to students in the Honor Code is the same trust that 
exists in and among researchers within a research community, the same trust 
that exists between us and our collaborators. Simply put, at Smith, under 
the Honor Code, I trust that you will each act with integrity, citing sources 
when you celebrate others’ ideas and noting who you work with when collaborating. 

This trust manifests in how assignments are created, in how work is completed, 
and in how we resolve instances where the trust has been broken. At an Honor Code 
school, assignments are created knowing that while there are resources online that 
can offer complete solutions, you are trusted to not seek out such complete 
resources and that if you do stumble on a solution guide, you will not use it. 
Under an Honor Code, students are expected to keep careful notes about the resources 
that they consult and the people that they collaborate with. We get to assume that 
the work handed in by a student is the creation of that student. Lastly, when there 
are violations of the Honor Code, the resolution is determined by a committee 
established by the community and trusted to seek restoration of the whole community’s 
trust through education and action. 

We regard the Honor Code with deep and profound respect. Being educators at an 
Honor Code school means we begin from a place of trust without any underlying 
suspicion of our students. Simply put, we - instructors and students - work from 
the assumption that all are acting in good faith and with the utmost integrity. 
This is an assumption that cannot be made at a school without an Honor code, 
and it is why it is a privilege to be both an instructor and a student at Smith 
under the Honor Code. 

## Honor Code Practicalities

The work you submit should be your own and created by you. We do encourage you 
to ask for help from your peers or myself when you have questions; however, 
copying is never allowed. The line between copying and helping is subtle. 
Below are a few guidelines:

* Do not share nor give your work with other students; instead, offer to discuss the big ideas of the task at hand. 
* Do not look at someone else’s work (including online solutions); instead, ask if you could talk with them about your ideas and share where you are getting stuck.
* Acknowledge those you talk or work with at the top of each assignment. We will not dock points for getting acknowledged help from others. If you generate a solution or an argument with someone, in addition to acknowledging that person, recreate the solution or argument on your own in your own words. 

If you think you may have crossed the line between helping and copying, please 
talk to your instructor or your lab instructor about it. Do not let us discover 
that the line was crossed. If a violation of the Honor Code is suspected, the 
student will be informed and will be given the opportunity to meet with the 
instructor. As recommended by the Academic Honor Board and in keeping with Smith 
tradition, the student will be given time to self-report, and after such time, 
the suspected violation will be reported to the Academic Honor Board by the instructor. 



***



# Accommodations {#accommodations}
 
Smith is committed to providing support services and reasonable accommodations to all students with disabilities. To request an accommodation, please register with the Disability Services Office at the beginning of the semester. To do so, call 413.585.2071 to arrange an appointment with Laura Rauscher, Director of Disability Services.

Once you have received an accommodation letter, please provided your instructor with a printed copy.



***



# Course Acknowledgements

Parts of this course - including slides, activities, and notes - will be from a variety of sources. Materials will be appropriately attributed and will be used in keeping with copyright and fair use laws. 



***



# Code of Conduct {#codeofconduct}

As the instructor and assistants for this course, we are committed to making
participation in this course a harassment-free experience for everyone,
regardless of level of experience, gender, gender identity and expression,
sexual orientation, disability, personal appearance, body size, race, ethnicity,
age, or religion. Examples of unacceptable behavior by participants in this
course include the use of sexual language or imagery, derogatory comments or
personal attacks, deliberate misgendering, trolling, public or private harassment, insults, or other
unprofessional conduct.

As the instructor and assistants we have the right and responsibility to point
out and stop behavior that is not aligned to this Code of Conduct. Participants
who do not follow the Code of Conduct may be reprimanded for such behavior.
Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the instructor.

**All students, the instructor, the lab instructor, and all assistants are
expected to adhere to this Code of Conduct in all settings for this course:
lectures, labs, office hours, tutoring hours, and over Slack.**

This Code of Conduct is adapted from the [Contributor
Covenant](http://contributor-covenant.org){target="_blank"}, version 1.0.0,
available [here](http://contributor-covenant.org/version/1/0/0/){target="_blank"}.

